### ISSUE TITLE
Training process?

### ISSUE THREAD

**Issue by gdolsten** [liu-bioinfo-lab/EPCOT#1]
Hi! Amazing work. I am curious, what was the training process for the model? How many GPU etc? What GPU does it fit on for inference time? I am very interested in applying this model for some interesting biological analyses!

**Comment by zzh24zzh** [comment]
> Hi! Amazing work. I am curious, what was the training process for the model? How many GPU etc? What GPU does it fit on for inference time? I am very interested in applying this model for some interesting biological analyses!

Thank you for your interest. We only used one V100 GPU to train each model. If you only use the trained model for inference, EPCOT doesn’t have a high requirement for GPU, like you can run the models on Google Colab notebook.
